# Generated by Django 3.2.7 on 2021-09-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
    ]
